package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/AnthonyThomasson/graph-ql/graph/generated"
	"github.com/AnthonyThomasson/graph-ql/graph/model"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.NewProduct) (*model.Product, error) {
	return r.createProduct(ctx, input)
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, page *model.PaginationInput, order *model.Order) (*model.ProductConnection, error) {
	return r.products(ctx, page, order)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
